### ISSUE TITLE
Can we get a new release published to npm?

### ISSUE THREAD

**Issue by justinmchase** [AssemblyScript/binaryen.js#3]
Specifically for this feature:
https://github.com/WebAssembly/binaryen/pull/1274

It appears to be in the latest build but the npm module is a couple of weeks old.

**Comment by justinmchase** [comment]
This realease:
https://github.com/WebAssembly/binaryen/releases/tag/1.37.23

**Comment by dcodeIO** [comment]
The bot publishes major version changes as releases only (the tags named `version_XY` on the parent repo). There is no versioning information present in between (the 1.37.XY tags are for emscripten integration specifically and not really versions), so everything else becomes a nightly (published once a day). The latest is `v39.0.0-nightly.20171202`, which you can install through:

```
npm install --save-exact binaryen@39.0.0-nightly.20171202
```

**Comment by dcodeIO** [comment]
Btw. the issue you linked initially hasn't been merged in this form. What has been merged, though, is https://github.com/WebAssembly/binaryen/pull/1292.

**Comment by justinmchase** [comment]
I specifically wanted this: `BinaryenAddMemoryImport`, and just snagging the `binaryen.js` file from the latest release seemed to have what I was looking for.

I'll nab that exact version! npm doesn't show you the full set of available versions on the site so I didn't realize that I could already get it. Thanks.

**Comment by justinmchase** [comment]
I seem to be unable to install from nightly, are you able to successfully install with that command you had above?

```bash
12:34:18:justin:/mnt/e/code/test$ npm install binaryen@nightly
npm WARN EINVAL: invalid argument, scandir '/mnt/e/code/test/node_modules/fsevents/node_modules/getpass/node_modules'
npm ERR! path /mnt/e/code/test/node_modules/binaryen/bin/as
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/mnt/e/code/test/node_modules/binaryen/bin/as'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2017-12-02T18_35_03_267Z-debug.log
```

**Comment by justinmchase** [comment]
```
npm install binaryen@39.0.0-nightly.20171121
```
The above installs successfully but the build from the 29th on doesn't.

**Comment by justinmchase** [comment]
This here appears to be the issue:
https://github.com/AssemblyScript/binaryen.js/blob/master/package.json#L17

That path isn't to a file, it should be `"binaryen-as": "bin/as.js",`

**Comment by justinmchase** [comment]
You're too fast 😛 

I'm just using the script manually for now I'll wait for the next nightly build. thanks.

**Comment by dcodeIO** [comment]
FYI: nightly just updated

**Comment by justinmchase** [comment]
It worked, all clear.
