### ISSUE TITLE
It is a very good project! Can you provide more code examples?

### ISSUE THREAD

**Issue by huge818** [AssemblyScript/binaryen.js#4]
It is a very good project! Can you provide more code examples?
It's a little difficult for me to understand

**Comment by dcodeIO** [comment]
Maybe take a look at the parent repository's JS test cases [here](https://github.com/WebAssembly/binaryen/tree/master/test/binaryen.js). Does that help?

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
