### ISSUE TITLE
Add wasm-metadce build

### ISSUE THREAD

**Issue by RReverser** [AssemblyScript/binaryen.js#41]
As the [original announcement](https://hacks.mozilla.org/2018/01/shrinking-webassembly-and-javascript-code-sizes-in-emscripten/) for [wasm-metadce](https://github.com/WebAssembly/binaryen/blob/master/src/tools/wasm-metadce.cpp) stated, it could be used for shrinking size of Wasm in JS bundlers. /cc @kripken @surma

However, right now there are no JS/Wasm builds of wasm-metadce, and the only place it's used in remains inside Emscripten.

Could we build metadce as a JS library as part of binaryen.js bots?

**Comment by dcodeIO** [comment]
> Could we build metadce as a JS library as part of binaryen.js bots?

I think so. Iirc Binaryen's build scripts already support building most, if not all, of the tools to JS so these can be run with node. While we are on it we may also investigate `wasm-as`, `wasm-dis` and `wasm2js` perhaps, if these seem useful to `npm install`.

**Comment by RReverser** [comment]
Yeah that sounds good. Although, aside from installing with node, I think important part of this is ability to run this tool as a library. For that, we'd need to also add a JS interface similarly to what binaryen.js does.

**Comment by dcodeIO** [comment]
Perhaps one option requiring little effort could be to support importing the tools in JS and call their main function as an API. Not as sophisticated as a proper library, but perhaps would already be helpful?

**Comment by kripken** [comment]
@dcodeIO I think that would be good. A generic way to turn a commandline tool into a library would let us get a lot of stuff working fast. The API might not be perfect but it would be a start to build a nicer API on top of. And doing it that way would avoid the need to refactor the metadce code into a library, etc.

I'm not sure exactly how that would work, but it seems like it could even be a generic option in upstream emscripten perhaps. But we can experiment with it in binaryen maybe, and see how it goes.

**Comment by dcodeIO** [comment]
> I'm not sure exactly how that would work, but it seems like it could even be a generic option in upstream emscripten perhaps.

Sounds good! Iirc this is typically done by checking whether the executing module is the main module, quite similar to how one would do that in Python with `__name__ == '__main__'`, and unconditionally export the `main` function. Something along the lines of:

```js
export function main(argv, options) {
  ...
  return code;
}

if (require.main === module) {
  process.exit(
    main(process.argv.slice(2), {
      stdout: process.stdout,
      stderr: process.stder
    })
  );
}
```

**Comment by RReverser** [comment]
I like this idea, yeah. Just one note: it should support passing stdin as well, as most JS build tools don't produce intermediate files and having to create those just for those tools would be not very ergonomic.

**Comment by dcodeIO** [comment]
There is a metadce build now.
