### ISSUE TITLE
Store returns an expression

### ISSUE THREAD

**Issue by SeboCode** [AssemblyScript/binaryen.js#5]
Is there a specific reason why the `store()` method returns an expression?
I think a statement would be much more fitting.

**Comment by MaxGraey** [comment]
Why you think statement better? According to [original](https://github.com/WebAssembly/binaryen/blob/230b9cd7f96eb3d7e35f07d4bb6f029264e6543c/src/binaryen-c.h#L369) method it should return expression reference.

**Comment by dcodeIO** [comment]
According to our typings, a `store` should probably be a `Statement` as you pointed out. Note, though, that the distinction between `Expression` and `Statement` is artificial here, as there are actually no statements in Binaryen itself. It might make sense to reflect that in our typings by removing `Statement` entirely, as that's pretty much just an `Expression` of type `None` anyway.

**Comment by SeboCode** [comment]
@MaxGraey The original binaryen API doesn't have a distinction between `Expression` and `Statement`. I think it should be a `Statement` just because of the logical factor that a `store()` to a memory does not create a value. Same goes for `setLocal()` which, in fact, is a `Statement` in the TypeScript API.

**Comment by SeboCode** [comment]
@dcodeIO Thanks for the quick answer. I think the distinction between `Expression` and `Statement` isn't a bad idea. It helps to not accidentally add an `Expression`, such as `1 + 2`, to e.g. a Block that should only take `Statements`. I'll change it to a `Statement` and open a pr.

**Comment by SeboCode** [comment]
Pullrequest: #6
