### ISSUE TITLE
commonjs

### ISSUE THREAD

**Issue by dvtate** [AssemblyScript/binaryen.js#63]
I have no idea when or why this package became an esm-only project but it should definitely offer both module systems or create a separate packages as converting my entire project over to esm has come with some new painpoints

**Comment by dvtate** [comment]
Also I feel like this is a more substantial breaking change an have no idea when it occured between v99.0.0 and v109.0.0... really I feel like this semver sysytem isn't right either

**Comment by MaxGraey** [comment]
> Also I feel like this is a more substantial breaking change an have no idea when it occured between v99.0.0 and v109.0.0... really I feel like this semver sysytem isn't right either

This just wrapper of native binaryen and version synced with native's version.

**Comment by dvtate** [comment]
the native's version is not v109.0.0 it's version_109

**Comment by MaxGraey** [comment]
> the native's version is not v109.0.0 it's version_109

That's right. They have the same major versions. I don't see any inconsistency here

**Comment by dvtate** [comment]
Just the 2 wasted subversions... Regardless, this is besides the point of breaking module compatibility. You can look at yargs for example of a package which supports both esm and commonjs

**Comment by judehunter** [comment]
I stumbled onto this as well. CommonJS builds should definitely be included...
