### ISSUE TITLE
How to create a stringref use string literals directly?

### ISSUE THREAD

**Issue by yviansu** [AssemblyScript/binaryen.js#69]
In [WebAssembly's stringref proposal](https://github.com/WebAssembly/stringref/blob/main/proposals/stringref/Overview.md), string literals can be used like this:
```
(global $hey stringref (string.const "Hey"))
```
And this will create a global variable $hey, which represents the reference of the string "Hey". I noticed binaryen has implemented this proposal, and added C-API bindings for the expression classes last week, including `StringConst` and `StringNew` etc.

However, I don't find the corresponding expression in binaryen.js. So I wonder is there any timeline for supporting the corresponding expression, so that binaryen.js can create a `stringref` use string literals directly?

**Comment by MaxGraey** [comment]
It's not yet ready. At least for cost string literals: https://github.com/WebAssembly/binaryen/pull/5024

**Comment by dcodeIO** [comment]
To use the existing parts now exposed via the C-API, what is missing to use them via the JS-API are the respective convenient bindings in the JS wrapper [around here](https://github.com/WebAssembly/binaryen/blob/d4d33b1e175c962548347c59339783c11d5d1a23/src/js/binaryen.js-post.js#L2445). If there is interest to add these, it's not complicated work I think, but it's a bunch of instructions to cover. In the meantime, it's also possible to use the C-API that is underlying the JS-API, by calling the `_BinaryenXY` exports directly. Not necessarily convenient, but the functionality is already there.

**Comment by yviansu** [comment]
@dcodeIO @MaxGraey  Thanks a lot for your reply!

Now I know how to use the C-API, the issue can be closed.
