### ISSUE TITLE
Release is single threaded

### ISSUE THREAD

**Issue by morenol** [AssemblyScript/binaryen.js#72]
It looks like binary output is single threaded, is it possible to make it multithreaded like the original binaryen binary?

**Comment by dcodeIO** [comment]
Iirc there has been some discussion about this in the past, where it was noted that the CLI tools could provide threading under Node.js - when specifically built for it. There might have been additional constraints for a universal build, like the bot currently produces, that also works in browsers.

Generally, this repo picks up the build script from [upstream Binaryen](https://github.com/WebAssembly/binaryen), so if threading support was added there (in case possible), the bot would build it.

**Comment by dcodeIO** [comment]
The CLI tools shipped with the package, e.g. wasm-opt, are multithreaded now iiuc.
