### ISSUE TITLE
How do create a data section in the IR

### ISSUE THREAD

**Issue by Dan-k391** [AssemblyScript/binaryen.js#76]
Sorry, I am not familiar with the operations here and the document is really insufficient.

Plz help.

**Comment by Dan-k391** [comment]
For example, how can I implement something such as ```(data (i32.const 0) "Hi")``` in binaryen IR

**Comment by CountBleck** [comment]
Try this:
```js
module.setMemory(
    initialSize,
    maximumSize,
    null,
    [
        {
            offset: module.i32.const(0),
            // If you're using Node.js, `Buffer.from("Hi")` also works 
            data: new Uint8Array([0x48, 0x69]),
            // I'm not sure what this does actually
            passive: false
        }
    ],
    false
)
```

**Comment by Dan-k391** [comment]
Thanks a lot but i am still kindof curious about what the passive param stands for, I hope they update the documents to a more detailed version

**Comment by CountBleck** [comment]
I'll have to look at Binaryen's docs or code, because the comment on the corresponding C function doesn't explain it either.

**Comment by CountBleck** [comment]
[This comment](https://github.com/WebAssembly/binaryen/blob/main/src/wasm-binary.h#L330-L332) appears to explain it...

**Comment by Dan-k391** [comment]
Thank you so much
