### ISSUE TITLE
`binaryen.Module.br_if` appears borken

### ISSUE THREAD

**Issue by AjaniBilby** [AssemblyScript/binaryen.js#84]
If I put a condition on a regular `br` statement (not sure why a regular br statement has an optional condition).
This will compile:
```js
ctx.m.br(ctx.popBlock(), ctx.m.i32.eq(
	m.local.get(success, binaryen.i32),
	m.i32.const(0)
))
```

But if I use the `br_if` function which sounds like the variant that should have the condition.
I always get an error
```js
m.br_if(ctx.popBlock(), ctx.m.i32.eq(
	m.local.get(success, binaryen.i32),
	m.i32.const(0)
))
```
I have no error messages I can give you as every time I get an error in binaryen my entire CLI history is blown out by a single line file that it's attempting to show a line reference in for the error.

**Proposal**: Ideally `br_if` should have a condition argument and `br` shouldn't, but you can't roll that backwithout breaking backwards compatibility. So if `br_if` is turely unfunctional - you should just remove it from the API completely since `br` does completely fulfill it's purpose.

**Comment by CountBleck** [comment]
`br_if` appears to be an alias to `br`. The [relevant code](https://github.com/WebAssembly/binaryen/blob/aaf1dac4/src/js/binaryen.js-post.js#L686) is outside of this repository, so this might not even be the right place to ask.

As to why you're experiencing a difference between the two functions: I have no idea.
